name: Naukri Updater Runner

on:
  schedule:
    # Every 30 minutes between 03:30–15:30 UTC (9 AM–9 PM IST)
    - cron: "30 3-15/1 * * *"
    - cron: "0 4-15/1 * * *"
  workflow_dispatch: # allows manual triggering

jobs:
  run-runner:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.APP_USERNAME }}
      PASSWORD: ${{ secrets.APP_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Maven
        run: mvn -q clean install
        working-directory: ./NaukriUpdater

      - name: Run Runner main method
        run: |
          echo "Running Runner..."
          mvn -q exec:java -Dexec.mainClass="updator.Runner"
        working-directory: ./NaukriUpdater

      - name: Upload screenshots
        if: always()  # ensures screenshots are uploaded even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: ./NaukriUpdater/screenshots/*.png
